### ISSUE TITLE
Mysticeti persistence tracker

### ISSUE THREAD

**Issue by andll** [MystenLabs/mysticeti#1]
Mysticeti persistence

- [x] Write blocks to wal
- [x] Wal iterator
- [x] Read wal in block store on startup
- [x] Other wal operations for core, proper recovery for core data structures
- [x] Recovery for certificate aggregator
- [x] Recovery for commit interpreter
- [x] Recovery for committed certificates aggregator
- [x] Real certified transactions handler for main.rs (log transactions to certified.txt)
- [x] Real commit handler for main.rs (log transactions to committed.txt)
- [x] Periodic cleanup wal reader mmap’s
- [x] Block store cache eviction, ensure not OOM during long run
- [x] Larger wal::MAP_SIZE
- [ ] Keep some blocks after replay in cache

Later
- [ ] Corner cases for wal, discard last entry(s) if they are corrupted
- [ ] Index file, do not replay main wal from the start
